import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_strings.dart';
import '../../../app/theme_controller.dart';
import '../../../common_widgets/view_common_widget/common_card_decoration.dart';
import 'controller/profile_setup_controller.dart';
import 'package:education_app/presentation/app/app_route.dart';
part 'profile_setup_view.dart';
