// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3bTtHkJrCNME_5gejgWf8_UG-R9mvyo',
    appId: '1:1079849551967:web:5b957e4e78cb798f0fb3ea',
    messagingSenderId: '1079849551967',
    projectId: 'beseda-74e08',
    authDomain: 'beseda-74e08.firebaseapp.com',
    storageBucket: 'beseda-74e08.firebasestorage.app',
    measurementId: 'G-98K1WNBPFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTwywLx4uHvZj0y7qMLjKxaCiOiNRcOU',
    appId: '1:1079849551967:android:89e349fa3e4d81300fb3ea',
    messagingSenderId: '1079849551967',
    projectId: 'beseda-74e08',
    storageBucket: 'beseda-74e08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEckZW6VKqbexO4eOWdegSMHg0kurWx4o',
    appId: '1:1079849551967:ios:91aeffffcc850ed50fb3ea',
    messagingSenderId: '1079849551967',
    projectId: 'beseda-74e08',
    storageBucket: 'beseda-74e08.firebasestorage.app',
    iosBundleId: 'com.app.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEckZW6VKqbexO4eOWdegSMHg0kurWx4o',
    appId: '1:1079849551967:ios:8609d2ae88d5dd5f0fb3ea',
    messagingSenderId: '1079849551967',
    projectId: 'beseda-74e08',
    storageBucket: 'beseda-74e08.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp3bTtHkJrCNME_5gejgWf8_UG-R9mvyo',
    appId: '1:1079849551967:web:03ad0f12e0f6eefb0fb3ea',
    messagingSenderId: '1079849551967',
    projectId: 'beseda-74e08',
    authDomain: 'beseda-74e08.firebaseapp.com',
    storageBucket: 'beseda-74e08.firebasestorage.app',
    measurementId: 'G-HYNV9T85J7',
  );
}
